export enum Permission {
  USERS_READ = 'USERS_READ',
  USERS_CREATE = 'USERS_CREATE',
  USERS_UPDATE = 'USERS_UPDATE',
  USERS_DELETE = 'USERS_DELETE',

  ESTABLISHMENTS_READ = 'ESTABLISHMENTS_READ',
  ESTABLISHMENTS_CREATE = 'ESTABLISHMENTS_CREATE',
  ESTABLISHMENTS_UPDATE = 'ESTABLISHMENTS_UPDATE',
  ESTABLISHMENTS_DELETE = 'ESTABLISHMENTS_DELETE',

  CONTRACTS_READ = 'CONTRACTS_READ',
  CONTRACTS_CREATE = 'CONTRACTS_CREATE',
  CONTRACTS_UPDATE = 'CONTRACTS_UPDATE',
  CONTRACTS_DELETE = 'CONTRACTS_DELETE',
  CONTRACTS_RENEW = 'CONTRACTS_RENEW',

  VEHICLES_READ = 'VEHICLES_READ',
  VEHICLES_CREATE = 'VEHICLES_CREATE',
  VEHICLES_UPDATE = 'VEHICLES_UPDATE',
  VEHICLES_DELETE = 'VEHICLES_DELETE',
  VEHICLES_IMPORT = 'VEHICLES_IMPORT',
  VEHICLES_EXPORT = 'VEHICLES_EXPORT',

  IMPORTS_IMPORT_ESTABLISHMENTS = 'IMPORTS_IMPORT_ESTABLISHMENTS',
  IMPORTS_IMPORT_TARIFICATION = 'IMPORTS_IMPORT_TARIFICATION',
  IMPORTS_EXPORT_SI = 'IMPORTS_EXPORT_SI',

  AUDIT_READ = 'AUDIT_READ',
  REPORTS_EXPORT = 'REPORTS_EXPORT',

  NOTIFICATIONS_READ = 'NOTIFICATIONS_READ',
  NOTIFICATIONS_GENERATE = 'NOTIFICATIONS_GENERATE',

  DOCUMENTS_READ = 'DOCUMENTS_READ',
  DOCUMENTS_GENERATE = 'DOCUMENTS_GENERATE',
}

export type Role = 'ADMIN' | 'MANAGER' | 'VIEWER';

export function getRolePermissions(role?: Role | string | null): Permission[] {
  const all = Object.values(Permission);
  switch (role) {
    case 'ADMIN':
      return all;
    case 'MANAGER':
      return all.filter(
        (p) =>
          !p.startsWith('USERS_') &&
          p !== Permission.AUDIT_READ &&
          p !== Permission.REPORTS_EXPORT,
      );
    case 'VIEWER':
      return all.filter(
        (p) =>
          p.endsWith('_READ') ||
          p === Permission.NOTIFICATIONS_READ ||
          p === Permission.DOCUMENTS_READ,
      );
    default:
      return [];
  }
}
